package:
  name: tem_circlefind
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - setuptools
    - pyqt <=5.0.0
    - setuptools_scm
    - matplotlib
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pyqt <=5.0.0

about:
  home: https://github.com/awacha/tem_circlefind
  license: BSD-3
  license_file: LICENSE

app:
  entry: tem_circlefind   [linux]
  entry: tem_circlefind   [win]
  icon: tem_circlefind.png
  summary: Circle finding tool for transmission electron micrographs
  type: desk
