package:
  name: tem_circlefind
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python >=3
    - setuptools
    - pyqt >=4
    - qtpy
    - setuptools_scm
    - matplotlib
    - numpy
    - scipy

  run:
    - python >=3
    - numpy
    - scipy
    - matplotlib
    - pyqt >=4
    - qtpy

about:
  home: https://github.com/awacha/tem_circlefind
  license: 3-clause BSD license
  dev_url: https://github.com/awacha/tem_circlefind.git
  license_family: BSD
  license_file: LICENSE
  summary: Circle finding tool for transmission electron micrographs
  description: A GUI utility for manually finding the position and diameter of circular objects in images

app:
  entry: tem_circlefind   [linux]
  entry: tem_circlefind   [win]
  summary: Circle finding tool for transmission electron micrographs
  type: desk
  icon: tem_circlefind.png
