# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/tem_circlefind/tem_circlefind.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_TEMCircleFind(object):
    def setupUi(self, TEMCircleFind):
        TEMCircleFind.setObjectName(_fromUtf8("TEMCircleFind"))
        TEMCircleFind.resize(997, 665)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TEMCircleFind.sizePolicy().hasHeightForWidth())
        TEMCircleFind.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(TEMCircleFind)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.clicktargetoperationBox = QtGui.QGroupBox(TEMCircleFind)
        self.clicktargetoperationBox.setEnabled(True)
        self.clicktargetoperationBox.setFlat(False)
        self.clicktargetoperationBox.setCheckable(True)
        self.clicktargetoperationBox.setChecked(True)
        self.clicktargetoperationBox.setObjectName(_fromUtf8("clicktargetoperationBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.clicktargetoperationBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.circlediameterRadioButton = QtGui.QRadioButton(self.clicktargetoperationBox)
        self.circlediameterRadioButton.setEnabled(True)
        self.circlediameterRadioButton.setChecked(True)
        self.circlediameterRadioButton.setObjectName(_fromUtf8("circlediameterRadioButton"))
        self.verticalLayout.addWidget(self.circlediameterRadioButton)
        self.threepointsRadioButton = QtGui.QRadioButton(self.clicktargetoperationBox)
        self.threepointsRadioButton.setEnabled(True)
        self.threepointsRadioButton.setObjectName(_fromUtf8("threepointsRadioButton"))
        self.verticalLayout.addWidget(self.threepointsRadioButton)
        self.calibrationRadioButton = QtGui.QRadioButton(self.clicktargetoperationBox)
        self.calibrationRadioButton.setEnabled(True)
        self.calibrationRadioButton.setObjectName(_fromUtf8("calibrationRadioButton"))
        self.verticalLayout.addWidget(self.calibrationRadioButton)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.clicktargetoperationBox)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.calibrationSpinBox = QtGui.QDoubleSpinBox(self.clicktargetoperationBox)
        self.calibrationSpinBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationSpinBox.sizePolicy().hasHeightForWidth())
        self.calibrationSpinBox.setSizePolicy(sizePolicy)
        self.calibrationSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.calibrationSpinBox.setDecimals(3)
        self.calibrationSpinBox.setMaximum(1e+20)
        self.calibrationSpinBox.setObjectName(_fromUtf8("calibrationSpinBox"))
        self.horizontalLayout_3.addWidget(self.calibrationSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.clicktargetoperationBox, 2, 1, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(TEMCircleFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 370, 282))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.resultsTreeWidget = QtGui.QTreeWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsTreeWidget.sizePolicy().hasHeightForWidth())
        self.resultsTreeWidget.setSizePolicy(sizePolicy)
        self.resultsTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.resultsTreeWidget.setColumnCount(3)
        self.resultsTreeWidget.setObjectName(_fromUtf8("resultsTreeWidget"))
        self.verticalLayout_2.addWidget(self.resultsTreeWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.removeselectedPushButton = QtGui.QPushButton(self.groupBox_3)
        self.removeselectedPushButton.setObjectName(_fromUtf8("removeselectedPushButton"))
        self.horizontalLayout_2.addWidget(self.removeselectedPushButton)
        self.clearresultsPushButton = QtGui.QPushButton(self.groupBox_3)
        self.clearresultsPushButton.setObjectName(_fromUtf8("clearresultsPushButton"))
        self.horizontalLayout_2.addWidget(self.clearresultsPushButton)
        self.saveresultsPushButton = QtGui.QPushButton(self.groupBox_3)
        self.saveresultsPushButton.setObjectName(_fromUtf8("saveresultsPushButton"))
        self.horizontalLayout_2.addWidget(self.saveresultsPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox_3, 4, 1, 1, 3)
        self.label = QtGui.QLabel(TEMCircleFind)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.widget = QtGui.QWidget(TEMCircleFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.figLayout = QtGui.QVBoxLayout()
        self.figLayout.setObjectName(_fromUtf8("figLayout"))
        self.verticalLayout_5.addLayout(self.figLayout)
        self.gridLayout.addWidget(self.widget, 0, 0, 5, 1)
        self.inputLineEdit = QtGui.QLineEdit(TEMCircleFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLineEdit.sizePolicy().hasHeightForWidth())
        self.inputLineEdit.setSizePolicy(sizePolicy)
        self.inputLineEdit.setObjectName(_fromUtf8("inputLineEdit"))
        self.gridLayout.addWidget(self.inputLineEdit, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(TEMCircleFind)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.browseInputButton = QtGui.QPushButton(TEMCircleFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseInputButton.sizePolicy().hasHeightForWidth())
        self.browseInputButton.setSizePolicy(sizePolicy)
        self.browseInputButton.setObjectName(_fromUtf8("browseInputButton"))
        self.gridLayout.addWidget(self.browseInputButton, 0, 3, 1, 1)
        self.pixelsizeSpinBox = QtGui.QDoubleSpinBox(TEMCircleFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixelsizeSpinBox.sizePolicy().hasHeightForWidth())
        self.pixelsizeSpinBox.setSizePolicy(sizePolicy)
        self.pixelsizeSpinBox.setDecimals(3)
        self.pixelsizeSpinBox.setMaximum(1e+26)
        self.pixelsizeSpinBox.setProperty("value", 1.0)
        self.pixelsizeSpinBox.setProperty("showGroupSeparator", False)
        self.pixelsizeSpinBox.setObjectName(_fromUtf8("pixelsizeSpinBox"))
        self.gridLayout.addWidget(self.pixelsizeSpinBox, 1, 2, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(TEMCircleFind)
        self.groupBox_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clicksTreeView = QtGui.QTreeWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clicksTreeView.sizePolicy().hasHeightForWidth())
        self.clicksTreeView.setSizePolicy(sizePolicy)
        self.clicksTreeView.setMinimumSize(QtCore.QSize(0, 10))
        self.clicksTreeView.setMaximumSize(QtCore.QSize(16777215, 100))
        self.clicksTreeView.setObjectName(_fromUtf8("clicksTreeView"))
        self.horizontalLayout.addWidget(self.clicksTreeView)
        self.forgetPushButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forgetPushButton.sizePolicy().hasHeightForWidth())
        self.forgetPushButton.setSizePolicy(sizePolicy)
        self.forgetPushButton.setObjectName(_fromUtf8("forgetPushButton"))
        self.horizontalLayout.addWidget(self.forgetPushButton)
        self.gridLayout.addWidget(self.groupBox_2, 3, 1, 1, 3)

        self.retranslateUi(TEMCircleFind)
        QtCore.QObject.connect(self.calibrationRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")),
                               self.label_2.setEnabled)
        QtCore.QObject.connect(self.calibrationRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")),
                               self.calibrationSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TEMCircleFind)

    def retranslateUi(self, TEMCircleFind):
        TEMCircleFind.setWindowTitle(_translate("TEMCircleFind", "TEM Circle Finder", None))
        self.clicktargetoperationBox.setTitle(
            _translate("TEMCircleFind", "Collect mouse clicks on the image for...", None))
        self.circlediameterRadioButton.setText(_translate("TEMCircleFind", "Circle diameter", None))
        self.threepointsRadioButton.setText(_translate("TEMCircleFind", "Three periferic points", None))
        self.calibrationRadioButton.setText(_translate("TEMCircleFind", "Pixel size calibration", None))
        self.label_2.setText(_translate("TEMCircleFind", "Calibrate selected distance to:", None))
        self.groupBox_3.setTitle(_translate("TEMCircleFind", "Results:", None))
        self.resultsTreeWidget.headerItem().setText(0, _translate("TEMCircleFind", "X coordinate", None))
        self.resultsTreeWidget.headerItem().setText(1, _translate("TEMCircleFind", "Y coordinate", None))
        self.resultsTreeWidget.headerItem().setText(2, _translate("TEMCircleFind", "Diameter", None))
        self.removeselectedPushButton.setText(_translate("TEMCircleFind", "Remove selected", None))
        self.clearresultsPushButton.setText(_translate("TEMCircleFind", "Clear", None))
        self.saveresultsPushButton.setText(_translate("TEMCircleFind", "Save...", None))
        self.label.setText(_translate("TEMCircleFind", "Input file:", None))
        self.label_3.setText(_translate("TEMCircleFind", "Pixel size:", None))
        self.browseInputButton.setText(_translate("TEMCircleFind", "Browse...", None))
        self.groupBox_2.setTitle(_translate("TEMCircleFind", "Clicks waiting for processing", None))
        self.clicksTreeView.headerItem().setText(0, _translate("TEMCircleFind", "X coordinate", None))
        self.clicksTreeView.headerItem().setText(1, _translate("TEMCircleFind", "Y coordinate", None))
        self.forgetPushButton.setText(_translate("TEMCircleFind", "Forget\n"
                                                                  "pending \n"
                                                                  "clicks", None))
